[build]
  command = "node inject-env.js"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  EMAILJS_PUBLIC_KEY = ""
  EMAILJS_SERVICE_ID = ""
  EMAILJS_TEMPLATE_ID = ""